openapi: 3.2.0
info:
  title: CIP-service Indexing Analysis Services API
  description: CIP-service is a project of the US Environmental Protection Agency Office of Water providing containers, logic and data for the task of associating or _indexing_ hydrologic features with NHDPlus features at multiple resolutions.  CIP-service supports a variety of purposes indexing to catchments, reaches or navigating the NHDPlus network for discovery or flow analysis. The majority of logic occurs within a containerized PostgreSQL database with additional containers providing support products such as an API, Jupyter Notebooks and sample demo applications. All components of the provided container stack are open source.
  termsOfService: https://www.epa.gov/web-policies-and-procedures/epa-disclaimers#geospatial
  contact:
    name: US EPA Office of Water
    url: https://www.epa.gov/aboutepa/about-office-water
  license:
    name: Creative Commons Zero v1.0 Universal
    identifier: CC0-1.0
  version: 1.5.2
servers:
- url: https://localhost:3000
  description: Change this endpoint as needed to your CIP-server PostgREST container
tags:
- name: Analysis Services
paths:
  /rpc/navigate:
    post:
      tags:
      - Analysis Services
      summary: CIP-service Navigation
      description: CIP-service Navigation Endpoint
      operationId: navigate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/navigate_rb'
            examples:
              navigateRequestExample:
                summary: Default navigate request
                x-microcks-default: true
                value: {}
      responses:
        '200':
          description: CIP-service Navigation Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/navigate_resp'
              examples:
                navigate200Example:
                  summary: Default navigate 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /rpc/delineate:
    post:
      tags:
      - Analysis Services
      summary: CIP-service Delineation
      description: CIP-service Delineation Endpoint
      operationId: delineate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delineate_rb'
            examples:
              delineateRequestExample:
                summary: Default delineate request
                x-microcks-default: true
                value: {}
      responses:
        '200':
          description: CIP-service Delineation Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delineate_resp'
              examples:
                delineate200Example:
                  summary: Default delineate 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /rpc/pointindexing:
    post:
      tags:
      - Analysis Services
      summary: CIP-service Point Indexing
      description: CIP-service Point Indexing Endpoint
      operationId: pointindexing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pointindexing_rb'
            examples:
              pointindexingRequestExample:
                summary: Default pointindexing request
                x-microcks-default: true
                value: {}
      responses:
        '200':
          description: CIP-service Point Indexing Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pointindexing_resp'
              examples:
                pointindexing200Example:
                  summary: Default pointindexing 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /rpc/upstreamdownstream:
    post:
      tags:
      - Analysis Services
      summary: CIP-service Upstream Downstream
      description: CIP-service Upstream Downstream Endpoint
      operationId: upstreamdownstream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/upstreamdownstream_rb'
            examples:
              upstreamdownstreamRequestExample:
                summary: Default upstreamdownstream request
                x-microcks-default: true
                value: {}
      responses:
        '200':
          description: CIP-service Upstream Downstream Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/upstreamdownstream_resp'
              examples:
                upstreamdownstream200Example:
                  summary: Default upstreamdownstream 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /rpc/flow_accumulation:
    post:
      tags:
      - Analysis Services
      summary: CIP-service Flow Accumulation
      description: CIP-service Flow Accumulation
      operationId: flow_accumulation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/flow_accumulation_rb'
            examples:
              flow_accumulationRequestExample:
                summary: Default flow_accumulation request
                x-microcks-default: true
                value: {}
      responses:
        '200':
          description: CIP-service Flow Accumulation Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/flow_accumulation_resp'
              examples:
                flow_accumulation200Example:
                  summary: Default flow_accumulation 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    geojson_feature:
      type:
      - object
      - 'null'
      title: GeoJSON Feature
      required:
      - type
      - geometry
      - properties
      externalDocs:
        url: https://tools.ietf.org/html/rfc7946#section-3.2
      properties:
        bbox:
          $ref: '#/components/schemas/geojson_bbox'
        geometry:
          $ref: '#/components/schemas/geojson_geometry'
        obj_type:
          type: string
          example: string
        properties:
          discriminator:
            propertyName: obj_type
            mapping:
              event_feature_properties: '#/components/schemas/event_feature_properties'
              indexed_catchment_properties: '#/components/schemas/indexed_catchment_properties'
              indexed_flowline_properties: '#/components/schemas/indexed_flowline_properties'
              navigated_flowline_properties: '#/components/schemas/navigated_flowline_properties'
              delineated_area_properties: '#/components/schemas/delineated_area_properties'
              end_point_properties: '#/components/schemas/end_point_properties'
              indexing_line_properties: '#/components/schemas/indexing_line_properties'
          oneOf:
          - $ref: '#/components/schemas/event_feature_properties'
          - $ref: '#/components/schemas/indexed_catchment_properties'
          - $ref: '#/components/schemas/indexed_flowline_properties'
          - $ref: '#/components/schemas/navigated_flowline_properties'
          - $ref: '#/components/schemas/delineated_area_properties'
          - $ref: '#/components/schemas/end_point_properties'
          - $ref: '#/components/schemas/indexing_line_properties'
          example: string
        type:
          type: string
          enum:
          - Feature
          example: Feature
    search_type:
      description: 'Navigation methodolody for network discovery of events:

        - UT = upstream with tributaries navigation

        - UM = upstream mainstem navigation

        - DM = downstream mainstem navigation

        - DD = downstream with divergences navigation

        - PP = point-to-point mainstem navigation

        - PPALL = point-to-point mainstem navigation with all streams between

        - UTNMD = upstream with tributaries no minor divergences navigation

        '
      type: string
      enum:
      - UM
      - UT
      - DM
      - DD
      - PP
      - PPALL
      examples:
      - UT
    return_delineation_geometry:
      description: Switch whether to return watershed or catchment geometry with results.
      type: boolean
      default: true
      examples:
      - true
    nhdplusid:
      description: NHDPlus int64 nhdplus identifier.
      type: integer
      format: int64
    fcode_allow:
      description: List of FCode values used for selecting a candidate reach measure.
      type: array
      items:
        type: number
    flow_accumulation_resp:
      type: object
      properties:
        flow_accumulation:
          type: string
          format: byte
          example: string
        image_format:
          $ref: '#/components/schemas/image_format'
        image_bbox:
          type: array
          items:
            type: number
          example:
          - 0.0
        max_accumulation:
          type: integer
          example: 35.5
        max_accumulation_x:
          type: integer
          example: 35.5
        max_accumulation_y:
          type: integer
          example: 35.5
        max_accumulation_pt:
          type: integer
          example: 35.5
        raster_srid:
          type: integer
          example: 0
        nhdplus_version:
          default: nhdplus_h
          $ref: '#/components/schemas/nhdplus_version'
        return_code:
          $ref: '#/components/schemas/return_code'
        status_message:
          $ref: '#/components/schemas/status_message'
    ordinate:
      type: number
      title: GeoJSON Ordinate
      examples:
      - -89.5327
    upstreamdownstream_rb:
      type: object
      properties:
        nhdplus_version:
          default: nhdplus_h
          $ref: '#/components/schemas/nhdplus_version'
        search_type:
          $ref: '#/components/schemas/search_type'
        start_nhdplusid:
          oneOf:
          - $ref: '#/components/schemas/start_nhdplusid'
          - type: 'null'
          example: '12345'
        start_permanent_identifier:
          oneOf:
          - $ref: '#/components/schemas/start_permanent_identifier'
          - type: 'null'
          example: '12345'
        start_reachcode:
          oneOf:
          - $ref: '#/components/schemas/start_reachcode'
          - type: 'null'
          example: string
        start_hydroseq:
          oneOf:
          - $ref: '#/components/schemas/start_hydroseq'
          - type: 'null'
          example: string
        start_measure:
          oneOf:
          - $ref: '#/components/schemas/start_measure'
          - type: 'null'
          example: string
        start_source_featureid:
          oneOf:
          - type: string
          - type: 'null'
          example: '12345'
        start_source_featureid2:
          oneOf:
          - type: string
          - type: 'null'
          example: '12345'
        start_source_originator:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        start_source_series:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        start_start_date:
          oneOf:
          - type: string
            format: date
          - type: 'null'
          example: string
        start_end_date:
          oneOf:
          - type: string
            format: date
          - type: 'null'
          example: string
        start_permid_joinkey:
          oneOf:
          - type: string
          - type: 'null'
          example: '12345'
        start_source_joinkey:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        start_cip_joinkey:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        start_linked_data_program:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        start_push_rad_for_permid:
          oneOf:
          - type: boolean
          - type: 'null'
          example: '12345'
        stop_nhdplusid:
          oneOf:
          - $ref: '#/components/schemas/stop_nhdplusid'
          - type: 'null'
          example: '12345'
        stop_permanent_identifier:
          oneOf:
          - $ref: '#/components/schemas/stop_permanent_identifier'
          - type: 'null'
          example: '12345'
        stop_reachcode:
          oneOf:
          - $ref: '#/components/schemas/stop_reachcode'
          - type: 'null'
          example: string
        stop_hydroseq:
          oneOf:
          - $ref: '#/components/schemas/stop_hydroseq'
          - type: 'null'
          example: string
        stop_measure:
          oneOf:
          - $ref: '#/components/schemas/stop_measure'
          - type: 'null'
          example: string
        stop_source_featureid:
          oneOf:
          - type: string
          - type: 'null'
          example: '12345'
        stop_source_featureid2:
          oneOf:
          - type: string
          - type: 'null'
          example: '12345'
        stop_source_originator:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        stop_source_series:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        stop_start_date:
          oneOf:
          - type: string
            format: date
          - type: 'null'
          example: string
        stop_end_date:
          oneOf:
          - type: string
            format: date
          - type: 'null'
          example: string
        stop_permid_joinkey:
          oneOf:
          - type: string
          - type: 'null'
          example: '12345'
        stop_source_joinkey:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        stop_cip_joinkey:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        stop_linked_data_program:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        stop_push_rad_for_permid:
          oneOf:
          - type: boolean
          - type: 'null'
          example: '12345'
        max_distancekm:
          oneOf:
          - $ref: '#/components/schemas/max_distancekm'
          - type: 'null'
          example: string
        max_flowtimeday:
          oneOf:
          - $ref: '#/components/schemas/max_flowtimeday'
          - type: 'null'
          example: string
        linked_data_search_list:
          type: array
          items:
            type: string
          example:
          - string
        search_precision:
          oneOf:
          - type: string
          - type: 'null'
          example: string
        return_flowlines:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        return_flowline_details:
          oneOf:
          - $ref: '#/components/schemas/return_flowline_details'
          - type: 'null'
          example: string
        return_flowline_geometry:
          oneOf:
          - $ref: '#/components/schemas/return_flowline_geometry'
          - type: 'null'
          example: string
        return_catchments:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        return_linked_data_cip:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        return_linked_data_huc12:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        return_linked_data_source:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        return_linked_data_rad:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        return_linked_data_attributes:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        remove_stop_start_sfids:
          oneOf:
          - type: boolean
          - type: 'null'
          example: '12345'
        push_source_geometry_as_rad:
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
    split_initial_catchment:
      description: Switch whether to split the initial catchment.  Splitting has a cost overhead and if not needed should be avoided.
      type: boolean
      default: false
      examples:
      - false
    reachcode:
      type: string
      minLength: 14
      maxLength: 14
    geojson_bbox:
      type: array
      title: GeoJSON BBox
      maxItems: 4
      minItems: 4
      items:
        $ref: '#/components/schemas/ordinate'
    delineated_area_properties:
      type: object
      properties:
        areasqkm:
          type: number
          example: 0.0
        hydroseq:
          $ref: '#/components/schemas/hydroseq'
        sourcefc:
          description: identifier of the delineation area source.
          type: string
          example: string
        nhdplusid:
          $ref: '#/components/schemas/nhdplusid'
    measure:
      type: number
      minimum: 0
      maximum: 100
    delineate_rb:
      type: object
      properties:
        nhdplus_version:
          default: nhdplus_h
          $ref: '#/components/schemas/nhdplus_version'
        search_type:
          $ref: '#/components/schemas/search_type'
        start_nhdplusid:
          oneOf:
          - $ref: '#/components/schemas/start_nhdplusid'
          - type: 'null'
          example: '12345'
        start_permanent_identifier:
          oneOf:
          - $ref: '#/components/schemas/start_permanent_identifier'
          - type: 'null'
          example: '12345'
        start_reachcode:
          oneOf:
          - $ref: '#/components/schemas/start_reachcode'
          - type: 'null'
          example: string
        start_hydroseq:
          oneOf:
          - $ref: '#/components/schemas/start_hydroseq'
          - type: 'null'
          example: string
        start_measure:
          oneOf:
          - $ref: '#/components/schemas/start_measure'
          - type: 'null'
          example: string
        stop_nhdplusid:
          oneOf:
          - $ref: '#/components/schemas/stop_nhdplusid'
          - type: 'null'
          example: '12345'
        stop_permanent_identifier:
          oneOf:
          - $ref: '#/components/schemas/stop_permanent_identifier'
          - type: 'null'
          example: '12345'
        stop_reachcode:
          oneOf:
          - $ref: '#/components/schemas/stop_reachcode'
          - type: 'null'
          example: string
        stop_hydroseq:
          oneOf:
          - $ref: '#/components/schemas/stop_hydroseq'
          - type: 'null'
          example: string
        stop_measure:
          oneOf:
          - $ref: '#/components/schemas/stop_measure'
          - type: 'null'
          example: string
        aggregation_engine:
          oneOf:
          - $ref: '#/components/schemas/aggregation_engine'
          - type: 'null'
          example: string
        max_distancekm:
          oneOf:
          - $ref: '#/components/schemas/max_distancekm'
          - type: 'null'
          example: string
        max_flowtimeday:
          oneOf:
          - $ref: '#/components/schemas/max_flowtimeday'
          - type: 'null'
          example: string
        split_initial_catchment:
          oneOf:
          - $ref: '#/components/schemas/split_initial_catchment'
          - type: 'null'
          example: string
        fill_basin_holes:
          oneOf:
          - $ref: '#/components/schemas/fill_basin_holes'
          - type: 'null'
          example: string
        return_delineation_geometry:
          oneOf:
          - $ref: '#/components/schemas/return_delineation_geometry'
          - type: 'null'
          example: string
        return_flowline_details:
          oneOf:
          - $ref: '#/components/schemas/return_flowline_details'
          - type: 'null'
          example: string
        return_flowline_geometry:
          oneOf:
          - $ref: '#/components/schemas/return_flowline_geometry'
          - type: 'null'
          example: string
    start_hydroseq:
      description: NHDPlus flowline hydro sequence bigint value from which to begin the navigation.
      type: integer
      format: int64
      examples:
      - 5000100019676
    return_flowline_details:
      description: Switch whether to return flowline details with results.
      type: boolean
      default: true
      examples:
      - true
    start_permanent_identifier:
      description: NHD flowline permanent identifier string value from which to begin the navigation.  Permanent Identifiers may manifest as text forms of the NHDPlusID or as 40-byte guid values.
      type: string
      maxLength: 40
      examples:
      - '{5DC9D377-46F7-41FB-A258-7A9AF8307610}'
    hydroseq:
      description: NHDPlus int64 hydro sequence identifier.
      type: integer
      format: int64
    flow_accumulation_rb:
      type: object
      properties:
        area_of_interest:
          $ref: '#/components/schemas/geojson_feature'
        default_weight:
          type: number
          example: 0.0
        known_region:
          $ref: '#/components/schemas/known_region'
        nhdplus_version:
          default: nhdplus_h
          $ref: '#/components/schemas/nhdplus_version'
        image_format:
          default: PNG
          $ref: '#/components/schemas/image_format'
        output_srid:
          type: integer
          example: 0
    globalid:
      type: string
      examples:
      - '{E374E06D-3A16-662D-E053-42DE4386FFB0}'
    geojson_featurecollection:
      type: object
      title: GeoJSON Feature Collection
      description: GeoJSon Feature collection
      required:
      - type
      - features
      externalDocs:
        url: https://tools.ietf.org/html/rfc7946#section-3.3
      properties:
        type:
          type: string
          enum:
          - FeatureCollection
          example: FeatureCollection
        features:
          type: array
          items:
            $ref: '#/components/schemas/geojson_feature'
          example:
          - string
    fcode_deny:
      description: List of FCode values avoided in selecting a candidate reach measure.
      type: array
      items:
        type: number
    flowline_count:
      description: Total count of flowlines returned from analysis.
      type: integer
      format: int32
    upstreamdownstream_resp:
      type: object
      properties:
        flowlines:
          $ref: '#/components/schemas/geojson_featurecollection'
        flowline_count:
          description: Total flowlines navigated by the search.
          type: integer
          format: int32
          examples:
          - 0
        catchments:
          $ref: '#/components/schemas/geojson_featurecollection'
        catchment_count:
          description: Total catchments returned by the search.
          type: integer
          format: int32
          examples:
          - 0
        linked_data_sfid_found:
          type: object
          properties:
            type:
              type: string
            rows:
              type: array
              items:
                type: object
                properties:
                  eventtype:
                    type: integer
                  source_originator:
                    type: string
                  source_featureid:
                    type: string
                  source_featureid2:
                    type: string
                  source_series:
                    type: string
                  source_subdivision:
                    type: string
                  source_joinkey:
                    type: string
                  start_date:
                    type: string
                    format: date
                  end_date:
                    type: string
                    format: date
                  sfiddetailurl:
                    type: string
                  src_event_count:
                    type: integer
                  rad_event_count:
                    type: integer
                  src_cat_joinkey_count:
                    type: integer
                  nearest_cip_distancekm_permid:
                    type: number
                  nearest_cip_distancekm_cat:
                    type: number
                  nearest_cip_network_distancekm:
                    type: number
                  nearest_rad_distancekm_permid:
                    type: string
                  nearest_rad_network_distancekm:
                    type: number
                  nearest_cip_flowtimeday_permid:
                    type: string
                  nearest_cip_flowtimeday_cat:
                    type: number
                  nearest_cip_network_flowtimeday:
                    type: number
                  nearest_rad_flowtimeday_permid:
                    type: string
                  nearest_rad_network_flowtimeday:
                    type: number
          example: {}
        linked_data_sfid_count:
          description: Total sfids discovered by the search.
          type: integer
          format: int32
          examples:
          - 0
        linked_data_cip_found:
          type: object
          properties:
            type:
              type: string
            rows:
              type: array
              items:
                type: object
                properties:
                  eventtype:
                    type: integer
                  permid_joinkey:
                    type: string
                  source_originator:
                    type: string
                  source_featureid:
                    type: string
                  source_featureid2:
                    type: string
                  source_series:
                    type: string
                  source_subdivision:
                    type: string
                  source_joinkey:
                    type: string
                  start_date:
                    type: string
                    format: date
                  end_date:
                    type: string
                    format: date
                  cat_joinkey:
                    type: string
                  catchmentstatecode:
                    type: string
                  nhdplusid:
                    type: integer
                    format: int64
                  xwalk_huc12:
                    type: string
                  network_distancekm:
                    type: number
                  network_flowtimeday:
                    type: number
          example: {}
        linked_data_cip_count:
          description: Total CIP indexed catchments discovered by the search.
          type: integer
          format: int32
          examples:
          - 0
        linked_data_huc12_found:
          type: object
          properties:
            type:
              type: string
            rows:
              type: array
              items:
                type: object
                properties:
                  eventtype:
                    type: integer
                  permid_joinkey:
                    type: string
                  source_originator:
                    type: string
                  source_featureid:
                    type: string
                  source_featureid2:
                    type: string
                  source_series:
                    type: string
                  source_subdivision:
                    type: string
                  source_joinkey:
                    type: string
                  start_date:
                    type: string
                    format: date
                  end_date:
                    type: string
                    format: date
                  xwalk_huc12:
                    type: string
                  network_distancekm:
                    type: number
                  network_flowtimeday:
                    type: number
          example: {}
        linked_data_huc12_count:
          description: Total CIP indexed xwalk HUC12s discovered by the search.
          type: integer
          format: int32
          examples:
          - 0
        linked_data_source_points:
          $ref: '#/components/schemas/geojson_feature'
        linked_data_source_lines:
          $ref: '#/components/schemas/geojson_feature'
        linked_data_source_areas:
          $ref: '#/components/schemas/geojson_feature'
        linked_data_source_count:
          description: Total source events discovered by the search.
          type: integer
          format: int32
          examples:
          - 0
        linked_data_reached_points:
          $ref: '#/components/schemas/geojson_feature'
        linked_data_reached_lines:
          $ref: '#/components/schemas/geojson_feature'
        linked_data_reached_areas:
          $ref: '#/components/schemas/geojson_feature'
        linked_data_reached_count:
          description: Total reach indexed events discovered by the search.
          type: integer
          format: int32
          examples:
          - 0
        linked_data_attributes:
          type: object
          properties:
            type:
              type: string
            rows:
              type: array
              items:
                oneOf:
                - $ref: '#/components/schemas/linked_data_wqp'
          example: {}
        start_nhdplusid:
          $ref: '#/components/schemas/nhdplusid'
        start_measure:
          $ref: '#/components/schemas/measure'
        start_linked_data_program:
          $ref: '#/components/schemas/linked_data_program'
        stop_nhdplusid:
          $ref: '#/components/schemas/nhdplusid'
        stop_measure:
          $ref: '#/components/schemas/measure'
        stop_linked_data_program:
          $ref: '#/components/schemas/linked_data_program'
        return_code:
          $ref: '#/components/schemas/return_code'
        status_message:
          $ref: '#/components/schemas/status_message'
    linked_data_wqp:
      type: object
      properties:
        source_joinkey:
          type: string
          example: string
        organizationidentifier:
          type: string
          example: '12345'
        organizationformalname:
          type: string
          example: EPA Facility
        monitoringlocationidentifier:
          type: string
          example: '12345'
        monitoringlocationname:
          type: string
          example: EPA Facility
        monitoringlocationtypename:
          type: string
          example: EPA Facility
        monitoringlocationdescription:
          type: string
          example: string
        huceightdigitcode:
          type: string
          example: string
        drainageareameasure_measureval:
          type: number
          example: 0.0
        drainageareameasure_measureunt:
          type: string
          example: string
        contributingdrainageareameasva:
          type: string
          example: string
        contributingdrainageareameasun:
          type: string
          example: string
        latitudemeasure:
          type: number
          example: 35.5
        longitudemeasure:
          type: number
          example: -78.0
        sourcemapscalenumeric:
          type: number
          example: 0.0
        horizontalaccuracymeasureval:
          type: string
          example: string
        horizontalaccuracymeasureunit:
          type: string
          example: string
        horizontalcollectionmethodname:
          type: string
          example: EPA Facility
        horizontalcoordinatereferences:
          type: string
          example: string
        verticalmeasure_measurevalue:
          type: string
          example: string
        verticalmeasure_measureunit:
          type: string
          example: string
        verticalaccuracymeasurevalue:
          type: string
          example: string
        verticalaccuracymeasureunit:
          type: string
          example: string
        verticalcollectionmethodname:
          type: string
          example: EPA Facility
        verticalcoordinatereferencesys:
          type: string
          example: string
        countrycode:
          type: string
          example: string
        statecode:
          type: string
          example: NC
        countycode:
          type: string
          example: '037'
        aquifername:
          type: string
          example: EPA Facility
        formationtypetext:
          type: string
          example: string
        aquifertypename:
          type: string
          example: EPA Facility
        constructiondatetext:
          type: string
          example: string
        welldepthmeasure_measurevalue:
          type: string
          example: string
        welldepthmeasure_measureunit:
          type: string
          example: string
        wellholedepthmeasure_measureva:
          type: string
          example: string
        wellholedepthmeasure_measureun:
          type: string
          example: string
        providername:
          type: string
          example: EPA Facility
        nearest_cip_network_distancekm:
          type: number
          example: 0.0
        nearest_cip_network_flowtimeday:
          type: number
          example: 0.0
        nearest_rad_network_distancekm:
          type: number
          example: 0.0
        nearest_rad_network_flowtimeday:
          type: number
          example: 0.0
    stop_measure:
      description: NHD flowline measure at which navigation will cease.  Only used in point-to-point navigation.
      type: number
      examples:
      - 45.23
    stop_reachcode:
      description: NHD flowline 14-byte reach code value from which navigation will cease.  Only used in point-to-point navigation.
      type: string
      minLength: 14
      maxLength: 14
      examples:
      - 188744699622
    indexed_catchment_properties:
      type: object
      properties:
        nhdplusid:
          $ref: '#/components/schemas/nhdplusid'
        catchmentstatecode:
          type: string
          example: NC
        xwalk_huc12:
          type:
          - string
          - 'null'
          minLength: 12
          maxLength: 12
          example: string
        areasqkm:
          type: number
          example: 0.0
    navigate_resp:
      type: object
      properties:
        flowlines:
          $ref: '#/components/schemas/geojson_featurecollection'
        flowline_count:
          $ref: '#/components/schemas/flowline_count'
        nhdplus_version:
          $ref: '#/components/schemas/nhdplus_version'
        return_code:
          $ref: '#/components/schemas/return_code'
        status_message:
          $ref: '#/components/schemas/status_message'
    event_feature_properties:
      type: object
      properties:
        globalid:
          $ref: '#/components/schemas/globalid'
        lengthkm:
          type: number
          example: 0.0
        areasqkm:
          type: number
          example: 0.0
        converted_to_ring:
          type: boolean
          example: true
        indexing_method_used:
          type: string
          example: string
        line_threshold_used:
          type: number
          example: 0.0
        areacat_threshold_used:
          type: number
          example: 0.0
        areaevt_threshold_used:
          type: number
          example: 0.0
    return_flowline_geometry:
      description: Switch whether to return flowline geometry information with results.
      type: boolean
      default: true
      examples:
      - true
    stop_hydroseq:
      description: NHDPlus flowline hydro sequence bigint value at which navigation will cease.  Only used in point-to-point navigation.
      type: integer
      format: int64
      examples:
      - 5000100000184
    max_flowtimeday:
      description: Maximum flow time traversed in hours for selecting features.  May not apply with all NHDPlus versions.
      type: number
      examples:
      - 1.2567
    coordinates2:
      type: array
      title: GeoJSON Coordinates 2
      items:
        $ref: '#/components/schemas/coordinates1'
    image_format:
      description: Desired output raster format.
      type: string
      enum:
      - PNG
      - GTIFF
      examples:
      - PNG
    start_nhdplusid:
      description: NHDPlus flowline NHDPlusID bigint value from which to begin the navigation.
      type: integer
      format: int64
      examples:
      - 5000100000184
    known_region:
      description: 'Provided value to use to determine the proper spatial reference system to use in geometric analysis. Providing an SRID value such as 5070 or a US state code such as MN will skip the sometimes expensive determination of the correct SRID for the feature. However, if the feature does not actually apply to the provide known_region hint, then indexing may fail or return incorrect results. If in doubt, leave this parameter blank.

        '
      type: string
    linked_data_program:
      type: string
    pointindexing_rb:
      type: object
      properties:
        point:
          oneOf:
          - $ref: '#/components/schemas/geojson_featurecollection'
          - $ref: '#/components/schemas/geojson_feature'
          - $ref: '#/components/schemas/geojson_geometry'
          example: string
        indexing_engine:
          oneOf:
          - $ref: '#/components/schemas/indexing_engine'
          - type: 'null'
          example: string
        fcode_allow:
          oneOf:
          - $ref: '#/components/schemas/fcode_allow'
          - type: 'null'
          example: string
        fcode_deny:
          oneOf:
          - $ref: '#/components/schemas/fcode_deny'
          - type: 'null'
          example: string
        distance_max_distkm:
          description: Maximum distance in kilometers the DISTANCE engine uses to find a reach measure candidate.
          oneOf:
          - type: number
          - type: 'null'
          example: string
        raindrop_snap_max_distkm:
          description: Maximum distance in kilometers the RAINDROP engine uses to snap to the final reach measure candidate.
          oneOf:
          - type: number
          - type: 'null'
          example: string
        raindrop_path_max_distkm:
          description: Maximum distance in kilometers the RAINDROP engine will travel towards a final candidate.
          oneOf:
          - type: number
          - type: 'null'
          example: string
        limit_innetwork:
          description: Flag to limit results to innetwork flowlines.
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        limit_navigable:
          description: Flag to limit results to navigable flowlines.
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        return_link_path:
          description: Flag whether to return a geometry representing the indexing path from start to candidate.
          oneOf:
          - type: boolean
          - type: 'null'
          example: string
        known_region:
          oneOf:
          - $ref: '#/components/schemas/known_region'
          - type: 'null'
          example: string
        known_catchment_nhdplusid:
          description: In some scenarios users may know the catchment NHDPlusID in which they desire to index.  Providing the value bypasses the cost of determining the catchment via spatial intersection.
          oneOf:
          - type: integer
          - type: 'null'
          example: '12345'
        nhdplus_version:
          default: nhdplus_h
          $ref: '#/components/schemas/nhdplus_version'
    status_message:
      description: Status message describing the results of processing.  Null indicates success.
      type:
      - string
      - 'null'
    max_distancekm:
      description: Maximum distance traversed in kilometers for selecting features.
      type: number
      examples:
      - 15
    start_reachcode:
      description: NHD flowline 14-byte reach code value from which to begin the navigation.  Provide a start measure to indicate a specific position on the reach.
      type: string
      minLength: 14
      maxLength: 14
      examples:
      - '01010007002110'
    navigated_flowline_properties:
      type: object
      properties:
        nhdplusid:
          $ref: '#/components/schemas/nhdplusid'
        hydroseq:
          $ref: '#/components/schemas/hydroseq'
        fmeasure:
          description: NHD flowline from measure.
          $ref: '#/components/schemas/measure'
        tmeasure:
          description: NHD flowline to measure.
          $ref: '#/components/schemas/measure'
        levelpathi:
          description: NHDPlus int64 level path identifier.
          type: integer
          format: int64
          example: 0
        terminalpa:
          description: NHDPlus int64 terminal path identifier.
          type: integer
          format: int64
          example: 0
        uphydroseq:
          description: NHDPlus int64 upstream flowline hydro sequence identifier.
          type: integer
          format: int64
          example: 0
        dnhydroseq:
          description: NHDPlus int64 downstream flowline hydro sequence identifier.
          type: integer
          format: int64
          example: 0
        lengthkm:
          description: length of the navigated flowline in kilometers.
          type: number
          example: 0.0
        flowtimeday:
          description: flow time in days of the navigated flowline.
          type: number
          example: 0.0
        network_distancekm:
          description: total length from start to the navigated flowline in kilometers.
          type: number
          example: 0.0
        network_flowtimeday:
          description: total flow time in days from start to the navigated flowline.
          type: number
          example: 0.0
        permanent_identifier:
          description: NHD permanent identifier of the navigated flowline.
          type:
          - string
          - 'null'
          example: '12345'
        reachcode:
          description: NHD reach code of the navigated flowline
          $ref: '#/components/schemas/reachcode'
        fcode:
          description: NHD feature type code of the navigated flowline.
          type: integer
          format: int32
          example: 0
        gnis_id:
          description: NHD GNIS identifier of the navigated flowline.
          type: string
          example: '12345'
        gnis_name:
          description: NHD GNIS name of the navigated flowline.
          type: string
          example: EPA Facility
        wbarea_permanent_identifier:
          description: NHD permanent identifier of the NHD waterbody feature associated with a flowline artificial path.
          type: string
          example: '12345'
        navtermination_flag:
          description: 'Integer code providing information about the navigated flowline within the context of the navigation. Valid codes are: 0. no termination 1. full termination 2. partial termination 3. coastal termination 4. headwater termination 5. network end termination (non-coastal)

            '
          type: integer
          format: int32
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          example: 0
        nav_order:
          description: rough ordering key placing flowlines in navigated order
          type: integer
          format: int32
          example: 0
    coordinates1:
      type: array
      title: GeoJSON Coordinates 1
      items:
        $ref: '#/components/schemas/ordinate'
    fill_basin_holes:
      description: Switch whether remove all holes from the returned watershed polygon.  This will remove isolated networks and sinks and may not be hydrologically correct.
      type: boolean
      default: false
      examples:
      - false
    stop_nhdplusid:
      description: NHDPlus flowline NHDPlusID bigint value at which navigation will cease.  Only used in point-to-point navigation.
      type: integer
      format: int64
      examples:
      - 5000100000184
    delineate_resp:
      type: object
      properties:
        delineated_area:
          obj_type: delineated_area_properties
          $ref: '#/components/schemas/geojson_featurecollection'
        aggregation_used:
          description: aggregation logic used in delineation action.
          type: string
          example: string
        flowlines:
          $ref: '#/components/schemas/geojson_featurecollection'
        flowline_count:
          $ref: '#/components/schemas/flowline_count'
        nhdplus_version:
          $ref: '#/components/schemas/nhdplus_version'
        return_code:
          $ref: '#/components/schemas/return_code'
        status_message:
          $ref: '#/components/schemas/status_message'
    navigate_rb:
      type: object
      properties:
        nhdplus_version:
          default: nhdplus_h
          $ref: '#/components/schemas/nhdplus_version'
        search_type:
          $ref: '#/components/schemas/search_type'
        start_nhdplusid:
          oneOf:
          - $ref: '#/components/schemas/start_nhdplusid'
          - type: 'null'
          example: '12345'
        start_permanent_identifier:
          oneOf:
          - $ref: '#/components/schemas/start_permanent_identifier'
          - type: 'null'
          example: '12345'
        start_reachcode:
          oneOf:
          - $ref: '#/components/schemas/start_reachcode'
          - type: 'null'
          example: string
        start_hydroseq:
          oneOf:
          - $ref: '#/components/schemas/start_hydroseq'
          - type: 'null'
          example: string
        start_measure:
          oneOf:
          - $ref: '#/components/schemas/start_measure'
          - type: 'null'
          example: string
        stop_nhdplusid:
          oneOf:
          - $ref: '#/components/schemas/stop_nhdplusid'
          - type: 'null'
          example: '12345'
        stop_permanent_identifier:
          oneOf:
          - $ref: '#/components/schemas/stop_permanent_identifier'
          - type: 'null'
          example: '12345'
        stop_reachcode:
          oneOf:
          - $ref: '#/components/schemas/stop_reachcode'
          - type: 'null'
          example: string
        stop_hydroseq:
          oneOf:
          - $ref: '#/components/schemas/stop_hydroseq'
          - type: 'null'
          example: string
        stop_measure:
          oneOf:
          - $ref: '#/components/schemas/stop_measure'
          - type: 'null'
          example: string
        max_distancekm:
          oneOf:
          - $ref: '#/components/schemas/max_distancekm'
          - type: 'null'
          example: string
        max_flowtimeday:
          oneOf:
          - $ref: '#/components/schemas/max_flowtimeday'
          - type: 'null'
          example: string
        return_flowline_details:
          oneOf:
          - $ref: '#/components/schemas/return_flowline_details'
          - type: 'null'
          example: string
        return_flowline_geometry:
          oneOf:
          - $ref: '#/components/schemas/return_flowline_geometry'
          - type: 'null'
          example: string
        known_region:
          oneOf:
          - $ref: '#/components/schemas/known_region'
          - type: 'null'
          example: string
    stop_permanent_identifier:
      description: NHD flowline permanent identifier string value from which navigation will cease.  Only used in point-to-point navigation.
      type: string
      maxLength: 40
      examples:
      - '{46D7557F-A83A-4414-AE56-105167EE3502}'
    aggregation_engine:
      description: Aggregation engine used to combine (or not) catchments into a watershed.
      type: string
      enum:
      - SPATIAL
      - TOPO
      - NONE
      examples:
      - SPATIAL
    nhdplus_version:
      description: NHDPlus version used in CIP indexing.
      type: string
      enum:
      - nhdplus_m
      - nhdplus_h
      examples:
      - nhdplus_h
    coordinates3:
      type: array
      title: GeoJSON Coordinates 3
      items:
        $ref: '#/components/schemas/coordinates2'
    indexed_flowline_properties:
      type: object
      properties:
        nhdplusid:
          $ref: '#/components/schemas/nhdplusid'
        gnis_id:
          description: NHD GNIS identifier
          type: string
          example: '12345'
        gnis_name:
          description: NHD GNIS name
          type: string
          example: EPA Facility
        reachcode:
          $ref: '#/components/schemas/reachcode'
        fmeasure:
          description: NHD flowline from measure.
          $ref: '#/components/schemas/measure'
        tmeasure:
          description: NHD flowline to measure.
          $ref: '#/components/schemas/measure'
    start_measure:
      description: NHD flowline measure from which to begin the navigation.
      type: number
      minimum: 0
      maximum: 100
      examples:
      - 50.0
    end_point_properties:
      type: object
      properties:
        nhdplus:
          description: NHDPlus int64 flowline identifier.
          type: integer
          format: int64
          example: 0
        reachcode:
          $ref: '#/components/schemas/reachcode'
        measure:
          $ref: '#/components/schemas/measure'
    return_code:
      description: Status code for results.  Zero indicates success.
      type: integer
      format: int32
      examples:
      - 0
    pointindexing_resp:
      type: object
      properties:
        flowlines:
          oneOf:
          - $ref: '#/components/schemas/geojson_featurecollection'
          - type: 'null'
          example: string
        path_distance_km:
          type: number
          example: 0.0
        end_point:
          oneOf:
          - $ref: '#/components/schemas/geojson_feature'
          - type: 'null'
          example: string
        indexing_line:
          oneOf:
          - $ref: '#/components/schemas/geojson_feature'
          - type: 'null'
          example: string
        region:
          type: string
          example: string
        nhdplusid:
          $ref: '#/components/schemas/nhdplusid'
        reachcode:
          $ref: '#/components/schemas/reachcode'
        hydroseq:
          $ref: '#/components/schemas/hydroseq'
        snap_measure:
          $ref: '#/components/schemas/measure'
        return_code:
          $ref: '#/components/schemas/return_code'
        status_message:
          type:
          - string
          - 'null'
          example: active
    geojson_geometry:
      type:
      - object
      - 'null'
      title: GeoJSON Geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometry-objects
      properties:
        coordinates:
          oneOf:
          - $ref: '#/components/schemas/coordinates1'
          - $ref: '#/components/schemas/coordinates2'
          - $ref: '#/components/schemas/coordinates3'
          - type: array
            title: GeoJSON Coordinates 4
            items:
              $ref: '#/components/schemas/coordinates3'
          example: string
        type:
          type: string
          enum:
          - Point
          - LineString
          - Polygon
          - MultiPoint
          - MultiLineString
          - MultiPolygon
          description: the geometry type
          example: Point
    indexing_line_properties:
      type: object
      properties:
        nhdplus:
          description: NHDPlus int64 flowline identifier.
          type: integer
          format: int64
          example: 0
    indexing_engine:
      description: Logic used to select a reach measure for indexing.
      type: string
      enum:
      - DISTANCE
      - RAINDROP
      - CATCONSTRAINED
      examples:
      - DISTANCE
