=== api-evangelist/epa/json-schema/cam-monitor-plan-monitor-plan-reporting-frequency-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/epa/refs/heads/main/json-schema/cam-monitor-plan-monitor-plan-reporting-frequency-schema.json",
  "title": "MonitorPlanReportingFrequency",
  "description": "MonitorPlanReportingFrequency schema from Monitor Plan Management OpenAPI Specification",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "12345"
    },
    "monitorPlanId": {
      "type": "string",
      "example": "12345"
    },
    "reportFrequencyCode": {
      "type": "string",
      "example": "string"
    },
    "beginReportPeriodId": {
      "type": "number",
      "example": 0.0
    },
    "endReportPeriodId": {
      "type": "number",
      "example": 0.0
    },
    "userId": {
      "type": "string",
      "example": "12345"
    },
    "addDate": {
      "format": "date-time",
      "type": "string",
      "example": "2024-01-15T12:00:00Z"
    },
    "updateDate": {
      "format": "date-time",
      "type": "string",
      "example": "2024-01-15T12:00:00Z"
    },
    "plan": {
      "$ref": "#/components/schemas/MonitorPlan"
    },
    "beginReportingPeriod": {
      "$ref": "#/components/schemas/ReportingPeriod"
    },
    "endReportingPeriod": {
      "$ref": "#/components/schemas/ReportingPeriod"
    }
  },
  "required": [
    "id",
    "monitorPlanId",
    "reportFrequencyCode",
    "beginReportPeriodId",
    "endReportPeriodId",
    "userId",
    "addDate",
    "updateDate",
    "plan",
    "beginReportingPeriod",
    "endReportingPeriod"
  ]
}

=== api-evangelist/epa/examples/cam-monitor-plan-monitor-plan-reporting-frequency-example.json
{
  "id": "12345",
  "monitorPlanId": "12345",
  "reportFrequencyCode": "string",
  "beginReportPeriodId": 0.0,
  "endReportPeriodId": 0.0,
  "userId": "12345",
  "addDate": "2024-01-15T12:00:00Z",
  "updateDate": "2024-01-15T12:00:00Z",
  "plan": "example",
  "beginReportingPeriod": "example",
  "endReportingPeriod": "example"
}
