=== api-evangelist/epa/json-schema/cam-qa-cert-review-and-submit-test-summary-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/epa/refs/heads/main/json-schema/cam-qa-cert-review-and-submit-test-summary-dto-schema.json",
  "title": "ReviewAndSubmitTestSummaryDTO",
  "description": "ReviewAndSubmitTestSummaryDTO schema from QA Certification Management OpenAPI Specification",
  "type": "object",
  "properties": {
    "orisCode": {
      "type": "number",
      "example": 0.0
    },
    "facilityName": {
      "type": "string",
      "example": "EPA Facility"
    },
    "monPlanId": {
      "type": "string",
      "example": "12345"
    },
    "locationInfo": {
      "type": "string",
      "example": "string"
    },
    "testSumId": {
      "type": "string",
      "example": "12345"
    },
    "systemComponentId": {
      "type": "string",
      "example": "12345"
    },
    "testTypeCode": {
      "type": "string",
      "example": "string"
    },
    "testNum": {
      "type": "string",
      "example": "string"
    },
    "beginDate": {
      "type": "string",
      "example": "string"
    },
    "endDate": {
      "type": "string",
      "example": "string"
    },
    "userId": {
      "type": "string",
      "example": "12345"
    },
    "updateDate": {
      "type": "string",
      "example": "string"
    },
    "evalStatusCode": {
      "type": "string",
      "example": "active"
    },
    "submissionAvailabilityCode": {
      "type": "string",
      "example": "string"
    },
    "evalStatusCodeDescription": {
      "type": "string",
      "example": "active"
    },
    "severityCode": {
      "type": "string",
      "example": "string"
    },
    "severityDescription": {
      "type": "string",
      "example": "string"
    },
    "submissionCodeDescription": {
      "type": "string",
      "example": "string"
    },
    "periodAbbreviation": {
      "type": "string",
      "example": "string"
    }
  },
  "required": [
    "orisCode",
    "facilityName",
    "monPlanId",
    "locationInfo",
    "testSumId",
    "systemComponentId",
    "testTypeCode",
    "testNum",
    "beginDate",
    "endDate",
    "userId",
    "updateDate",
    "evalStatusCode",
    "submissionAvailabilityCode",
    "evalStatusCodeDescription",
    "severityCode",
    "severityDescription",
    "submissionCodeDescription",
    "periodAbbreviation"
  ]
}

=== api-evangelist/epa/examples/cam-qa-cert-review-and-submit-test-summary-dto-example.json
{
  "orisCode": 0.0,
  "facilityName": "EPA Facility",
  "monPlanId": "12345",
  "locationInfo": "string",
  "testSumId": "12345",
  "systemComponentId": "12345",
  "testTypeCode": "string",
  "testNum": "string",
  "beginDate": "string",
  "endDate": "string",
  "userId": "12345",
  "updateDate": "string",
  "evalStatusCode": "active",
  "submissionAvailabilityCode": "string",
  "evalStatusCodeDescription": "active",
  "severityCode": "string",
  "severityDescription": "string",
  "submissionCodeDescription": "string",
  "periodAbbreviation": "string"
}
