=== api-evangelist/epa/json-schema/cam-monitor-plan-mats-method-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/epa/refs/heads/main/json-schema/cam-monitor-plan-mats-method-schema.json",
  "title": "MatsMethod",
  "description": "MatsMethod schema from Monitor Plan Management OpenAPI Specification",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "12345"
    },
    "locationId": {
      "type": "string",
      "example": "12345"
    },
    "supplementalMATSParameterCode": {
      "type": "string",
      "example": "string"
    },
    "supplementalMATSMonitoringMethodCode": {
      "type": "string",
      "example": "string"
    },
    "beginDate": {
      "format": "date-time",
      "type": "string",
      "example": "2024-01-15T12:00:00Z"
    },
    "beginHour": {
      "type": "number",
      "example": 0.0
    },
    "endDate": {
      "format": "date-time",
      "type": "string",
      "example": "2024-01-15T12:00:00Z"
    },
    "endHour": {
      "type": "number",
      "example": 0.0
    },
    "userId": {
      "type": "string",
      "example": "12345"
    },
    "addDate": {
      "format": "date-time",
      "type": "string",
      "example": "2024-01-15T12:00:00Z"
    },
    "updateDate": {
      "format": "date-time",
      "type": "string",
      "example": "2024-01-15T12:00:00Z"
    },
    "location": {
      "$ref": "#/components/schemas/MonitorLocation"
    }
  },
  "required": [
    "id",
    "locationId",
    "supplementalMATSParameterCode",
    "supplementalMATSMonitoringMethodCode",
    "beginDate",
    "beginHour",
    "endDate",
    "endHour",
    "userId",
    "addDate",
    "updateDate",
    "location"
  ]
}

=== api-evangelist/epa/examples/cam-monitor-plan-mats-method-example.json
{
  "id": "12345",
  "locationId": "12345",
  "supplementalMATSParameterCode": "string",
  "supplementalMATSMonitoringMethodCode": "string",
  "beginDate": "2024-01-15T12:00:00Z",
  "beginHour": 0.0,
  "endDate": "2024-01-15T12:00:00Z",
  "endHour": 0.0,
  "userId": "12345",
  "addDate": "2024-01-15T12:00:00Z",
  "updateDate": "2024-01-15T12:00:00Z",
  "location": "example"
}
