=== api-evangelist/epa/json-schema/cam-monitor-plan-pctqualification-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/epa/refs/heads/main/json-schema/cam-monitor-plan-pctqualification-dto-schema.json",
  "title": "PCTQualificationDTO",
  "description": "PCTQualificationDTO schema from Monitor Plan Management OpenAPI Specification",
  "type": "object",
  "properties": {
    "qualificationYear": {
      "type": "number",
      "description": "The calendar year during which activity occurred.",
      "example": 2020
    },
    "averagePercentValue": {
      "type": "number",
      "description": "The average percent capacity or heat input usage.",
      "example": 100
    },
    "yr1QualificationDataYear": {
      "type": "number",
      "description": "The first year corresponding to the qualification data.",
      "example": 2018
    },
    "yr1QualificationDataTypeCode": {
      "type": "string",
      "description": "Code used to identify the type qualification in the first year.",
      "example": "A"
    },
    "yr1PercentageValue": {
      "type": "number",
      "description": "The percent capacity or heat input usage in the first year.",
      "example": 100
    },
    "yr2QualificationDataYear": {
      "type": "number",
      "description": "The second year corresponding to the qualification data.",
      "example": 2019
    },
    "yr2QualificationDataTypeCode": {
      "type": "string",
      "description": "Code used to identify the type qualification in the second year.",
      "example": "A"
    },
    "yr2PercentageValue": {
      "type": "number",
      "description": "The percent capacity or heat input usage in the second year.",
      "example": 100
    },
    "yr3QualificationDataYear": {
      "type": "number",
      "description": "The third year corresponding to the qualification data.",
      "example": 2020
    },
    "yr3QualificationDataTypeCode": {
      "type": "string",
      "description": "Code used to indicate type of data for year (actual or projected) used to determine peaking or gas-fired qualification.",
      "example": "A"
    },
    "yr3PercentageValue": {
      "type": "number",
      "description": "The percent capacity or heat input usage in the third year.",
      "example": 100
    },
    "id": {
      "type": "string",
      "description": "Unique identifier of a monitoring qualification percentage record.",
      "example": "02227-BSGR-56EB0D4D400642A4860D6402698BBE16"
    },
    "qualificationId": {
      "type": "string",
      "description": "Unique identifier of a monitoring qualification record.",
      "example": "02022-614W-608B84AEDB8148C7B3935EE935AB835F"
    },
    "userId": {
      "type": "string",
      "description": "User account or source of data that added or updated record.",
      "example": "abcde"
    },
    "addDate": {
      "type": "string",
      "description": "Date and time in which record was added.",
      "example": "2021-04-01"
    },
    "updateDate": {
      "type": "string",
      "description": "Date and time in which record was last updated.",
      "example": "2021-04-01"
    }
  },
  "required": [
    "qualificationYear",
    "averagePercentValue",
    "yr1QualificationDataYear",
    "yr1QualificationDataTypeCode",
    "yr1PercentageValue",
    "yr2QualificationDataYear",
    "yr2QualificationDataTypeCode",
    "yr2PercentageValue",
    "yr3QualificationDataYear",
    "yr3QualificationDataTypeCode",
    "yr3PercentageValue",
    "id",
    "qualificationId",
    "userId",
    "addDate",
    "updateDate"
  ]
}

=== api-evangelist/epa/examples/cam-monitor-plan-pctqualification-dto-example.json
{
  "qualificationYear": 2020,
  "averagePercentValue": 100,
  "yr1QualificationDataYear": 2018,
  "yr1QualificationDataTypeCode": "A",
  "yr1PercentageValue": 100,
  "yr2QualificationDataYear": 2019,
  "yr2QualificationDataTypeCode": "A",
  "yr2PercentageValue": 100,
  "yr3QualificationDataYear": 2020,
  "yr3QualificationDataTypeCode": "A",
  "yr3PercentageValue": 100,
  "id": "02227-BSGR-56EB0D4D400642A4860D6402698BBE16",
  "qualificationId": "02022-614W-608B84AEDB8148C7B3935EE935AB835F",
  "userId": "abcde",
  "addDate": "2021-04-01",
  "updateDate": "2021-04-01"
}
