=== api-evangelist/epa/json-schema/echo-dfr-dfr022-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/epa/refs/heads/main/json-schema/echo-dfr-dfr022-schema.json",
  "title": "dfr022",
  "description": "FRV Programs Pollutant Object",
  "type": "object",
  "properties": {
    "Agency": {
      "description": "Identifies the lead agency (e.g., EPA, State) conducting the inspection. \nValues: State abbreviation or \"EPA\"",
      "example": "State",
      "title": "Agency",
      "type": "string"
    },
    "AirPollutants": {
      "description": "The air pollutant(s) for which the facility is in violation.",
      "example": "Benzene, TOTAL PARTICULATE MATTER, FACIL",
      "title": "AIR Pollutants",
      "type": "string"
    },
    "AirPrograms": {
      "description": "The air program under to which the facility or operation is subject.",
      "example": "CAANESH, CAASIP, CAATVP",
      "title": "AIR Programs",
      "type": "string"
    },
    "ERPType": {
      "description": "Air Facility System (AFS) ID.",
      "example": "VA0000005151044014",
      "title": "Enforcement Response Policy Type Identifier",
      "type": "string"
    },
    "Mnth10Status": {
      "description": "The compliance status of the tenth month.",
      "example": "No Violation Identified",
      "title": "Month 10 Status",
      "type": "string"
    },
    "Mnth11Status": {
      "description": "The compliance status of the eleventh month.",
      "example": "No Violation Identified",
      "title": "Month 11 Status",
      "type": "string"
    },
    "Mnth12Status": {
      "description": "The compliance status of the twelfth month.",
      "example": "No Violation Identified",
      "title": "Month 12 Status",
      "type": "string"
    },
    "Mnth13Status": {
      "description": "The compliance status of the thirteenth month.",
      "example": "No Violation Identified",
      "title": "Month 13 Status",
      "type": "string"
    },
    "Mnth14Status": {
      "description": "The compliance status of the fourteenth month.",
      "example": "No Violation Identified",
      "title": "Month 14 Status",
      "type": "string"
    },
    "Mnth15Status": {
      "description": "The compliance status of the fifteenth month.",
      "example": "No Violation Identified",
      "title": "Month 15 Status",
      "type": "string"
    },
    "Mnth16Status": {
      "description": "The compliance status of the sixteenth month.",
      "example": "No Violation Identified",
      "title": "Month 16 Status",
      "type": "string"
    },
    "Mnth17Status": {
      "description": "The compliance status of the seventeenth month.",
      "example": "No Violation Identified",
      "title": "Month 17 Status",
      "type": "string"
    },
    "Mnth18Status": {
      "description": "The compliance status of the eighteenth month.",
      "example": "No Violation Identified",
      "title": "Month 18 Status",
      "type": "string"
    },
    "Mnth19Status": {
      "description": "The compliance status of the ninteenth month.",
      "example": "No Violation Identified",
      "title": "Month 19 Status",
      "type": "string"
    },
    "Mnth1Status": {
      "description": "The compliance status of the first month.",
      "example": "No Violation Identified",
      "title": "Month 1 Status",
      "type": "string"
    },
    "Mnth20Status": {
      "description": "The compliance status of the twentieth month.",
      "example": "No Violation Identified",
      "title": "Month 20 Status",
      "type": "string"
    },
    "Mnth21Status": {
      "description": "The compliance status of the twenty-first month.",
      "example": "No Violation Identified",
      "title": "Month 21 Status",
      "type": "string"
    },
    "Mnth22Status": {
      "description": "The compliance status of the twenty-second month.",
      "example": "No Violation Identified",
      "title": "Month 22 Status",
      "type": "string"
    },
    "Mnth23Status": {
      "description": "The compliance status of the twenty-third month.",
      "example": "No Violation Identified",
      "title": "Month 23 Status",
      "type": "string"
    },
    "Mnth24Status": {
      "description": "The compliance status of the twenty-fourth month.",
      "example": "No Violation Identified",
      "title": "Month 24 Status",
      "type": "string"
    },
    "Mnth25Status": {
      "description": "The compliance status of the twenty-fifth month.",
      "example": "No Violation Identified",
      "title": "Month 25 Status",
      "type": "string"
    },
    "Mnth26Status": {
      "description": "The compliance status of the twenty-sixth month.",
      "example": "No Violation Identified",
      "title": "Month 26 Status",
      "type": "string"
    },
    "Mnth27Status": {
      "description": "The compliance status of the twenty-seventh month.",
      "example": "No Violation Identified",
      "title": "Month 27 Status",
      "type": "string"
    },
    "Mnth28Status": {
      "description": "The compliance status of the twenty-eighth month.",
      "example": "No Violation Identified",
      "title": "Month 28 Status",
      "type": "string"
    },
    "Mnth29Status": {
      "description": "The compliance status of the twenty-ninth month.",
      "example": "No Violation Identified",
      "title": "Month 29 Status",
      "type": "string"
    },
    "Mnth2Status": {
      "description": "The compliance status of the second month.",
      "example": "No Violation Identified",
      "title": "Month 2 Status",
      "type": "string"
    },
    "Mnth30Status": {
      "description": "The compliance status of the thirtieth month.",
      "example": "No Violation Identified",
      "title": "Month 30 Status",
      "type": "string"
    },
    "Mnth31Status": {
      "description": "The compliance status of the thirty-first month.",
      "example": "No Violation Identified",
      "title": "Month 31 Status",
      "type": "string"
    },
    "Mnth32Status": {
      "description": "The compliance status of the thirty-second month.",
      "example": "No Violation Identified",
      "title": "Month 32 Status",
      "type": "string"
    },
    "Mnth33Status": {
      "description": "The compliance status of the thirty-third month.",
      "example": "No Violation Identified",
      "title": "Month 33 Status",
      "type": "string"
    },
    "Mnth34Status": {
      "description": "The compliance status of the thirty-fourth month.",
      "example": "No Violation Identified",
      "title": "Month 34 Status",
      "type": "string"
    },
    "Mnth35Status": {
      "description": "The compliance status of the thirty-fifth month.",
      "example": "No Violation Identified",
      "title": "Month 35 Status",
      "type": "string"
    },
    "Mnth36Status": {
      "description": "The compliance status of the thirty-sixth month.",
      "example": "No Violation Identified",
      "title": "Month 36 Status",
      "type": "string"
    },
    "Mnth3Status": {
      "description": "The compliance status of the third month.",
      "example": "No Violation Identified",
      "title": "Month 3 Status",
      "type": "string"
    },
    "Mnth4Status": {
      "description": "The compliance status of the fourth month.",
      "example": "No Violation Identified",
      "title": "Month 4 Status",
      "type": "string"
    },
    "Mnth5Status": {
      "description": "The compliance status of the fifth month.",
      "example": "No Violation Identified",
      "title": "Month 5 Status",
      "type": "string"
    },
    "Mnth6Status": {
      "description": "The compliance status of the sixth month.",
      "example": "No Violation Identified",
      "title": "Month 6 Status",
      "type": "string"
    },
    "Mnth7Status": {
      "description": "The compliance status of the seventh month.",
      "example": "No Violation Identified",
      "title": "Month 7 Status",
      "type": "string"
    },
    "Mnth8Status": {
      "description": "The compliance status of the eighth month.",
      "example": "No Violation Identified",
      "title": "Month 8 Status",
      "type": "string"
    },
    "Mnth9Status": {
      "description": "The compliance status of the ninth month.",
      "example": "No Violation Identified",
      "title": "Month 9 Status",
      "type": "string"
    },
    "Qtr10Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 10 Status",
      "type": "string"
    },
    "Qtr11Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 11 Status",
      "type": "string"
    },
    "Qtr12Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 12 Status",
      "type": "string"
    },
    "Qtr1Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 1 Status",
      "type": "string"
    },
    "Qtr2Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 2 Status",
      "type": "string"
    },
    "Qtr3Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 3 Status",
      "type": "string"
    },
    "Qtr4Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 4 Status",
      "type": "string"
    },
    "Qtr5Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 5 Status",
      "type": "string"
    },
    "Qtr6Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 6 Status",
      "type": "string"
    },
    "Qtr7Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 7 Status",
      "type": "string"
    },
    "Qtr8Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 8 Status",
      "type": "string"
    },
    "Qtr9Status": {
      "description": "The relevant status for the quarter.",
      "example": "No Viol",
      "title": "Quarter 9 Status",
      "type": "string"
    },
    "SourceID": {
      "description": "Unique Identifier assigned by EPA.",
      "example": "ALR040033",
      "title": "EPA Source Identifier",
      "type": "string"
    }
  },
  "required": [
    "SourceID",
    "ERPType",
    "AirPrograms",
    "AirPollutants",
    "Qtr1Status",
    "Qtr2Status",
    "Qtr3Status",
    "Qtr4Status",
    "Qtr5Status",
    "Qtr6Status",
    "Qtr7Status",
    "Qtr8Status",
    "Qtr9Status",
    "Qtr10Status",
    "Qtr11Status",
    "Qtr12Status",
    "Mnth1Status",
    "Mnth2Status",
    "Mnth3Status",
    "Mnth4Status",
    "Mnth5Status",
    "Mnth6Status",
    "Mnth7Status",
    "Mnth8Status",
    "Mnth9Status",
    "Mnth10Status",
    "Mnth11Status",
    "Mnth12Status",
    "Mnth13Status",
    "Mnth14Status",
    "Mnth15Status",
    "Mnth16Status",
    "Mnth17Status",
    "Mnth18Status",
    "Mnth19Status",
    "Mnth20Status",
    "Mnth21Status",
    "Mnth22Status",
    "Mnth23Status",
    "Mnth24Status",
    "Mnth25Status",
    "Mnth26Status",
    "Mnth27Status",
    "Mnth28Status",
    "Mnth29Status",
    "Mnth30Status",
    "Mnth31Status",
    "Mnth32Status",
    "Mnth33Status",
    "Mnth34Status",
    "Mnth35Status",
    "Mnth36Status",
    "Agency"
  ]
}

=== api-evangelist/epa/examples/echo-dfr-dfr023-example.json
{
  "Agency": "State",
  "AirPollutants": "Benzene, TOTAL PARTICULATE MATTER, FACIL",
  "AirPrograms": "CAANESH, CAASIP, CAATVP",
  "ERPType": "VA0000005151044014",
  "Mnth10Status": "No Violation Identified",
  "Mnth11Status": "No Violation Identified",
  "Mnth12Status": "No Violation Identified",
  "Mnth13Status": "No Violation Identified",
  "Mnth14Status": "No Violation Identified",
  "Mnth15Status": "No Violation Identified",
  "Mnth16Status": "No Violation Identified",
  "Mnth17Status": "No Violation Identified",
  "Mnth18Status": "No Violation Identified",
  "Mnth19Status": "No Violation Identified",
  "Mnth1Status": "No Violation Identified",
  "Mnth20Status": "No Violation Identified",
  "Mnth21Status": "No Violation Identified",
  "Mnth22Status": "No Violation Identified",
  "Mnth23Status": "No Violation Identified",
  "Mnth24Status": "No Violation Identified",
  "Mnth25Status": "No Violation Identified",
  "Mnth26Status": "No Violation Identified",
  "Mnth27Status": "No Violation Identified",
  "Mnth28Status": "No Violation Identified",
  "Mnth29Status": "No Violation Identified",
  "Mnth2Status": "No Violation Identified",
  "Mnth30Status": "No Violation Identified",
  "Mnth31Status": "No Violation Identified",
  "Mnth32Status": "No Violation Identified",
  "Mnth33Status": "No Violation Identified",
  "Mnth34Status": "No Violation Identified",
  "Mnth35Status": "No Violation Identified",
  "Mnth36Status": "No Violation Identified",
  "Mnth3Status": "No Violation Identified",
  "Mnth4Status": "No Violation Identified",
  "Mnth5Status": "No Violation Identified",
  "Mnth6Status": "No Violation Identified",
  "Mnth7Status": "No Violation Identified",
  "Mnth8Status": "No Violation Identified",
  "Mnth9Status": "No Violation Identified",
  "Qtr10Status": "No Viol",
  "Qtr11Status": "No Viol",
  "Qtr12Status": "No Viol",
  "Qtr1Status": "No Viol",
  "Qtr2Status": "No Viol",
  "Qtr3Status": "No Viol",
  "Qtr4Status": "No Viol",
  "Qtr5Status": "No Viol",
  "Qtr6Status": "No Viol",
  "Qtr7Status": "No Viol",
  "Qtr8Status": "No Viol",
  "Qtr9Status": "No Viol",
  "SourceID": "ALR040033"
}
